coretabs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path(url_path, include((pattern_list, app_name), namespace=instance_name))
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('hello/<str:name>/', views.hello),
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.products_list, name='products_list'),
    path('products/by_category/', views.products_by_category,
         name='products_by_category'),
    path('<str:slug>/', views.products_list, name='products_list'),
    path('products/<str:slug>/<int:id>/',
         views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse_lazy


class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, max_length=256)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ('name', '-created_at',)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(blank=True)

    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE)

    class Meta:
        ordering = ('name', 'price', '-created_at')

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('shop:product_detail', args=(self.slug, self.id))

    def __str__(self):
        return "{0} {1}".format(self.name, self.stock)

coretabs/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hi there, this is our new home page.")


def hello(request, name):
    return HttpResponse("Hello {}".format(name))

shop/views.py
from django.shortcuts import render, get_object_or_404


from .models import Category, Product


def products_list(request, slug=None):
    categories = Category.objects.all()
    if not slug:
        products = Product.objects.all()
        title = "All"
    else:
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category=category)
        title = category.name
    return render(request, 'shop/list.html',
                  {'title': title,
                   'products': products,
                   'categories': categories})


def products_by_category(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    title = "By Category"
    return render(request, 'shop/products_by_category.html',
                  {'title': title,
                   'products': products,
                   'categories': categories})


def product_detail(request, slug, id):
    product = get_object_or_404(Product, slug=slug)
    categories = Category.objects.all()
    title = "Produect Detail"
    return render(request, 'shop/detail.html',
                  {'title': title,
                   'product': product,
                   'categories': categories})

shop/templates/shop/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    {% load static %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">

    <title>{% block title %}Coretbas shop{% endblock title%}</title>
</head>

<body class="container-fluid bg-light">
    <header class='shadow p-3 mb-5 bg-dark rounded text-uppercase'>
        {% block header %}
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
                <a class="navbar-brand" href="/">Coretabs Shop
                    {% load static %}
                    <img src="{% static "img/shop_icon.png" %}"  width="30" height="30" alt="shop-icon"/>
                </a>    
              </nav>
        {% endblock header %}
    </header>

    <main id="content" class="container-fluid">
        {% block main %}    
            <div class="row">   
                <aside class="col-3">
                    {% block sidenav %}{% endblock sidenav %}
                </aside>
                <div class="col-9">
                    {% block content %}{% endblock content %}
                </div>
            </div> 
         {% endblock main%}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script> 
    {% load static %}
    <script src="{% static "js/bootstrap.js" %}" " integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T
        " crossorigin="anonymous "></script>
</body>

</html>

shop/templates/shop/detail.html
{% extends "shop/list.html" %}
{% block title %} Product Detail {% endblock title %}
{% block content %}
<h1>{{ product.name }}</h1>
<ul>
    <li>Price: {{ product.price }}</li>
    <li>Available Quantity: {{ product.stock }}</li>
    <li>Description: {{ product.description }}</li>
</ul>
{% endblock content %}

shop/templates/shop/list.html
{% extends "shop/base.html" %} {% block title %} {{ title }} Products {% endblock title %} {% block sidenav %}
<nav class="nav flex-column">
    <a class="nav-link" href="{% url 'shop:products_list' %}">All Products</a>
    <ul>
        <li>
            <a class="text-right" href="{% url 'shop:products_by_category' %}">By categories</a>
        </li>
    </ul>
    {% for category in categories %}
    <a class="nav-link" href="{% url 'shop:products_list' category.slug %} ">{{ category.name }}</a>
    {% endfor %}
</nav>
{% endblock sidenav %} {% block content %}
<ul class="list-group ">
    {% for product in products %}
    <li class='list-group-item'>
        <a href="{{ product.get_absolute_url }} ">{{ product.name }}</a>
        <br> Price: {{ product.price }}
        <br> Description: {{ product.description }}
    </li>
    {% endfor %}
</ul>
{% endblock content %}

shop/templates/shop/products_by_category.html
{% extends "shop/list.html" %} {% block content %} {% for category in categories %}
<br>
<h2>{{ category.name }}</h2>
<ul class="list-group">
    {% for product in products %} {% if category == product.category %}
    <li class='list-group-item'>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br> Price: {{ product.price }}
        <br> Description: {{ product.description}}
    </li>
    {% endif %} {% endfor %}
</ul>


{% endfor %} {% endblock content %}